name: dott_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pandas
  - scipy
  - numpy
  - pysam
  - matplotlib
  - seaborn
  - rpy2
  - mygene
  - subread
  - r-base
  - bioconductor-deseq2
  - bioconductor-enhancedvolcano
  - r-ggplot2
  - r-svglite
  - r-argparse
  - scikit-learn
  - imbalanced-learn
  
